doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Gift:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/Gift/Domain/Entity'
                prefix: 'App\Core\Gift\Domain\Entity'
                alias: Gift
            Employee:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/Employee/Domain/Entity'
                prefix: 'App\Core\Employee\Domain\Entity'
                alias: Employee
            User:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/User/Domain/Entity'
                prefix: 'App\Core\User\Domain\Entity'
                alias: User
