#controllersPost:
#        resource: ../../src/Blog/Post/Application/Controller/
#        type: annotation
ControllerGifts:
        resource: ../../src/Core/Gift/Application/Controller/
        type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
