#Create employee
#curl --location --request POST 'https://localhost/api/employee/'
#--header 'Content-Type: application/json'
#--data-raw ' {
#     "name": "Vasya "
#      }'
POST https://localhost/api/employee/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NDY4MDMwMDgsImV4cCI6MTY0NjgwNjYwOCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6InRlc3QzQGdtYWlsLmNvbSJ9.1BCMxUsnb9V9nD1CeJWGk1lEt07L9psOv_SZLtXv1Cf3B4JcN77lU1tEd9PdKKUYDqjtKwFdL62AL84SkhBYmruVK-cyBRq6IA5LxPo6yUndXra9m-52vOwcsXAxvsk0Fdp9FAWq5x_wTbJCM8Zt11mAd1LQRcYM-LPiw22W6iZA5UBtzLUDSUlhtRmxxgwzAYqGnAbtam0LJy2jh3x4Zkc6LiS4YXLlUsav8L5PR7KKy0Ph190PMbmVjbPFLuclhjBpadW6M6UXkCMfZZOTmjHarqIL8vhN4xT7qPhqbHfdNXvJFeX3WtgyNp1pQroPthI0aKMUcgFlRuvgAwjPtg
Cookie: PHPSESSID=r0o95epalfm6mroiv8eovv4pam
Content-Type: application/json

{
  "name": "Vasya "
}

### Create employee and add interests

POST https://localhost/api/employee/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2NDY4MDMwMDgsImV4cCI6MTY0NjgwNjYwOCwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6InRlc3QzQGdtYWlsLmNvbSJ9.1BCMxUsnb9V9nD1CeJWGk1lEt07L9psOv_SZLtXv1Cf3B4JcN77lU1tEd9PdKKUYDqjtKwFdL62AL84SkhBYmruVK-cyBRq6IA5LxPo6yUndXra9m-52vOwcsXAxvsk0Fdp9FAWq5x_wTbJCM8Zt11mAd1LQRcYM-LPiw22W6iZA5UBtzLUDSUlhtRmxxgwzAYqGnAbtam0LJy2jh3x4Zkc6LiS4YXLlUsav8L5PR7KKy0Ph190PMbmVjbPFLuclhjBpadW6M6UXkCMfZZOTmjHarqIL8vhN4xT7qPhqbHfdNXvJFeX3WtgyNp1pQroPthI0aKMUcgFlRuvgAwjPtg
Cookie: PHPSESSID=r0o95epalfm6mroiv8eovv4pam
Content-Type: application/json

{
  "name": "Vasya ",
  "interestIds": [
    "47e68532-21b1-45a5-a4f6-e3c8248e5ae6"
  ]
}

###

